# Generated by Django 4.1.7 on 2023-04-08 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='book',
            new_name='books',
        ),
    ]
